### ISSUE TITLE
FP4 factory image available

### ISSUE THREAD

**Issue by maximilianovermeyer** [WeAreFairphone/android_device_fairphone_FP4#7]
Hi there,
the firmware image is now officially available!
https://support.fairphone.com/hc/en-us/articles/4405858261777
I am currently on mobile and did not run the script to extract the blobs 'til now, so have mercy if it doesn't work like expected. Will probably have a look in the afternoon.

**Comment by maximilianovermeyer** [comment]
Extract the zip and check md5 of images/super.img.
Then use simg2img to convert the image.
Use the following offsets to get the complete image:
048576       **0x100000**        Linux EXT filesystem, blocks count: 294353, image size: 301417472, rev 1.0, ext2 filesystem data, UUID=d4faaf93-50c4-59e1-a45c-a18bfbfefbfe, volume name "**/**"

1226833920   **0x49200000**      Linux EXT filesystem, blocks count: 85898, image size: 87959552, rev 1.0, ext2 filesystem data, UUID=aca590e1-8e02-5ad7-8fd0-132b68506850, volume name "**system_ext**"

1585446912   **0x5E800000**      Linux EXT filesystem, blocks count: 447922, image size: 458672128, rev 1.0, ext2 filesystem data, UUID=094c0bd1-96b4-5238-a46d-b250269d269d, volume name "**product**"

3449815040   **0xCDA00000**      Linux EXT filesystem, blocks count: 165115, image size: 169077760, rev 1.0, ext2 filesystem data, UUID=398b0030-dbb2-5090-ae2e-ad6a384b384b, volume name "**vendor**"

Example `sudo mount super.raw -t ext4 -o ro,loop,offset=0x100000 ./FP4_root/`

**Comment by z3ntu** [comment]
Probably easier to use this tool? https://github.com/tchebb/parse-android-dynparts

**Comment by maximilianovermeyer** [comment]
Giving it a quick try, it fails:
```
nope@nope:~/android$ sudo losetup -r /dev/loop20 super.raw
nope@nope:~/android$ sudo dmsetup create --concise "$(parse-android-dynparts /dev/loop20)"
[E][liblp]std::unique_ptr<android::fs_mgr::LpMetadata> android::fs_mgr::ReadMetadata(const string&, uint32_t) open failed: /dev/loop20
Failed to parse metadata from "/dev/loop20"
```
But should be worth to give it a deeper look, seems to be the way better option in general.

**Comment by z3ntu** [comment]
parse-android-dynparts also needs root/sudo

**Comment by maximilianovermeyer** [comment]
Yes, worked flawlessly this time and I got offered all partitions. Thanks for the tip!
